/**
 * 97 WORLD — YOUTUBE BOOST
 *
 * Data only. The flow lives in /assets/wizard.js and is identical on every
 * order page. Generated by tools/build-order-pages.mjs — edit that, not this.
 *
 * Prices are USD; UGX is derived at 3,750 UGX = $1.
 */
OrderWizard.start({
    "sheetUrl": "https://script.google.com/macros/s/AKfycbzsER7toUR8OwPWPic7Oqbbjz-ew2pR_HJ4Um3V9o6eVmlf730ibwF7ELv6GCekmgl2aA/exec",
    "whatsapp": "256762193386",
    "storeKey": "k97_region_yt",
    "service": "YouTube Boost",
    "targetLabel": "YouTube channel",
    "targetError": "We need the channel to deliver to",
    "plans": [
        {
            "id": "yt5",
            "name": "Domination",
            "usd": 400,
            "tag": "Max impact",
            "hero": true,
            "label": "Domination Tier",
            "feats": [
                {
                    "icon": "fa-users",
                    "text": "10k subs",
                    "gold": true
                },
                {
                    "icon": "fa-eye",
                    "text": "15k views"
                },
                {
                    "icon": "fa-thumbs-up",
                    "text": "10k likes"
                }
            ]
        },
        {
            "id": "yt4",
            "name": "Viral",
            "usd": 310,
            "label": "Viral Tier",
            "feats": [
                {
                    "icon": "fa-users",
                    "text": "7.5k subs"
                },
                {
                    "icon": "fa-eye",
                    "text": "13k views"
                },
                {
                    "icon": "fa-thumbs-up",
                    "text": "8k likes"
                }
            ]
        },
        {
            "id": "yt3",
            "name": "Authority",
            "usd": 230,
            "label": "Authority Tier",
            "feats": [
                {
                    "icon": "fa-users",
                    "text": "5.5k subs"
                },
                {
                    "icon": "fa-eye",
                    "text": "11k views"
                },
                {
                    "icon": "fa-thumbs-up",
                    "text": "6.5k likes"
                }
            ]
        },
        {
            "id": "yt2",
            "name": "Growth",
            "usd": 160,
            "tag": "Most popular",
            "label": "Growth Tier",
            "feats": [
                {
                    "icon": "fa-users",
                    "text": "3.5k subs"
                },
                {
                    "icon": "fa-eye",
                    "text": "9k views"
                },
                {
                    "icon": "fa-thumbs-up",
                    "text": "5k likes"
                }
            ]
        },
        {
            "id": "yt1",
            "name": "Kickstart",
            "usd": 110,
            "label": "Kickstart Tier",
            "feats": [
                {
                    "icon": "fa-users",
                    "text": "2k subs"
                },
                {
                    "icon": "fa-eye",
                    "text": "7k views"
                },
                {
                    "icon": "fa-thumbs-up",
                    "text": "3.5k likes"
                }
            ]
        },
        {
            "id": "yt0",
            "name": "Starter",
            "usd": 70,
            "tag": "Starter",
            "label": "Starter Tier",
            "feats": [
                {
                    "icon": "fa-users",
                    "text": "1k subs"
                },
                {
                    "icon": "fa-eye",
                    "text": "5k views"
                },
                {
                    "icon": "fa-thumbs-up",
                    "text": "2k likes"
                }
            ]
        }
    ],
    "gifts": [
        {
            "icon": "fa-rotate-left",
            "title": "30-day refill guarantee",
            "sub": "Anything that drops off inside 30 days, we top back up. Free."
        },
        {
            "icon": "fa-comments",
            "title": "Free profile review",
            "sub": "We'll tell you what's holding your page back, on WhatsApp."
        }
    ],
    "proof": [
        {
            "icon": "fa-lock",
            "title": "We never ask for your password",
            "body": "Delivery works entirely from your public handle. Your login stays yours."
        },
        {
            "icon": "fa-bolt",
            "title": "You watch it start before you finish paying",
            "body": "The first batch lands in 1–6 hours. 30% starts the order, the balance is due once delivery is running."
        },
        {
            "icon": "fa-location-dot",
            "title": "We are actually here",
            "body": "Kampala-based. Pay by MTN or Airtel Money, or bring cash to the office."
        }
    ]
});
