/**
 * 97 WORLD — TIKTOK BOOST
 *
 * Data only. The flow lives in /assets/wizard.js and is identical on every
 * order page. Generated by tools/build-order-pages.mjs — edit that, not this.
 *
 * Prices are USD; UGX is derived at 3,750 UGX = $1.
 */
OrderWizard.start({
    "sheetUrl": "https://script.google.com/macros/s/AKfycbzsER7toUR8OwPWPic7Oqbbjz-ew2pR_HJ4Um3V9o6eVmlf730ibwF7ELv6GCekmgl2aA/exec",
    "whatsapp": "256762193386",
    "platform": "tt",
    "service": "TikTok Boost",
    "targetLabel": "TikTok username",
    "targetError": "We need the username to deliver to",
    "gifts": [
        {
            "icon": "fa-rotate-left",
            "title": "30-day refill guarantee",
            "sub": "Anything that drops off inside 30 days, we top back up. Free."
        },
        {
            "icon": "fa-comments",
            "title": "Free profile review",
            "sub": "We'll tell you what's holding your page back, on WhatsApp."
        }
    ],
    "proof": [
        {
            "icon": "fa-lock",
            "title": "We never ask for your password",
            "body": "Delivery works entirely from your public handle. Your login stays yours."
        },
        {
            "icon": "fa-bolt",
            "title": "You watch it start before you finish paying",
            "body": "The first batch lands in 1–6 hours. 30% starts the order, the balance is due once delivery is running."
        },
        {
            "icon": "fa-location-dot",
            "title": "We are actually here",
            "body": "Kampala-based. Pay by MTN or Airtel Money, or bring cash to the office."
        }
    ]
});
