/**
 * 97 WORLD — PERPLEXITY PRO
 *
 * Data only. The flow lives in /assets/wizard.js and is identical on every
 * order page. Generated by tools/build-order-pages.mjs — edit that, not this.
 *
 * Prices are USD; UGX is derived at 3,750 UGX = $1.
 */
OrderWizard.start({
    "sheetUrl": "https://script.google.com/macros/s/AKfycbzsER7toUR8OwPWPic7Oqbbjz-ew2pR_HJ4Um3V9o6eVmlf730ibwF7ELv6GCekmgl2aA/exec",
    "whatsapp": "256762193386",
    "apiBase": "https://the97-orders.carteluganda.workers.dev",
    "platform": "perplexity-pro",
    "service": "Perplexity Pro",
    "depositPct": 1,
    "gifts": [
        {
            "icon": "fa-rotate",
            "title": "Replacement guarantee",
            "sub": "If access stops working during your paid period, we replace it. Free."
        },
        {
            "icon": "fa-comments",
            "title": "Real support, not a ticket queue",
            "sub": "Message us on WhatsApp any time — a person replies, not a bot."
        }
    ],
    "proof": [
        {
            "icon": "fa-key",
            "title": "Simple, upfront pricing",
            "body": "Pick your months, pay once — no recurring charge, no surprise renewal."
        },
        {
            "icon": "fa-rotate",
            "title": "Replaced if it breaks",
            "body": "If access stops working during your paid period, we sort it — free, same account."
        },
        {
            "icon": "fa-location-dot",
            "title": "We are actually here",
            "body": "Kampala-based. Pay by MTN or Airtel Money, or bring cash to the office."
        }
    ]
});
